# Generated by Django 5.1.3 on 2024-11-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ootd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ootd_photo',
        ),
    ]
