# Generated by Django 5.1.3 on 2024-11-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='satisfaction',
            field=models.IntegerField(choices=[(1, 'Cold'), (2, 'Neutral'), (3, 'Hot')]),
        ),
    ]
