# Generated by Django 5.1.3 on 2024-11-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('outer', '아우터'), ('top', '상의'), ('bottom', '하의'), ('other', '기타')], max_length=10)),
                ('warmth_level', models.IntegerField(choices=[(1, 'Level 1: 매우 더운 날씨 (30°C 이상)'), (2, 'Level 2: 더운 날씨 (23°C ~ 29°C)'), (3, 'Level 3: 선선한 날씨 (15°C ~ 22°C)'), (4, 'Level 4: 쌀쌀한 날씨 (5°C ~ 14°C)'), (5, 'Level 5: 매우 추운 날씨 (5°C 이하)')])),
            ],
        ),
    ]
