# Generated by Django 5.1.3 on 2024-11-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='is_frequent',
            field=models.BooleanField(default=False),
        ),
    ]
